// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-bO0NIfJZ3GRy2ekR3lgnkyDkBMQLx4I',
    appId: '1:641243027761:web:2e6404bff0fd4d6560f810',
    messagingSenderId: '641243027761',
    projectId: 'joy-ai-9f03f',
    authDomain: 'joy-ai-9f03f.firebaseapp.com',
    storageBucket: 'joy-ai-9f03f.appspot.com',
    measurementId: 'G-KE9CM2X1W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCezUYJXw1hmp4aSYB1isNciJdY6QS-nGQ',
    appId: '1:641243027761:android:e0f56b00ebbce9a560f810',
    messagingSenderId: '641243027761',
    projectId: 'joy-ai-9f03f',
    storageBucket: 'joy-ai-9f03f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO8NMmTuZlzw2oJkYYBqiCc6Elj9HhvLk',
    appId: '1:641243027761:ios:00349f1b4c80804660f810',
    messagingSenderId: '641243027761',
    projectId: 'joy-ai-9f03f',
    storageBucket: 'joy-ai-9f03f.appspot.com',
    iosClientId: '641243027761-okad2pj34hvj5ve4g5qcsttom6reaboq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO8NMmTuZlzw2oJkYYBqiCc6Elj9HhvLk',
    appId: '1:641243027761:ios:3f8fc7a0f97531b560f810',
    messagingSenderId: '641243027761',
    projectId: 'joy-ai-9f03f',
    storageBucket: 'joy-ai-9f03f.appspot.com',
    iosClientId: '641243027761-7pb2eknrbs72fngbnv1i0t4enptuadpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTest1.RunnerTests',
  );
}
